name: Build AutomationDesigner

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore AutomationDesigner.sln

    - name: Disable VSTO signing tasks
      shell: powershell
      run: |
        $targets = "C:\Program Files\Microsoft Visual Studio\18\Enterprise\MSBuild\Microsoft\VisualStudio\v18.0\OfficeTools\Microsoft.VisualStudio.Tools.Office.targets"

        Write-Host "Patching VSTO targets file:"
        Write-Host $targets

        $content = Get-Content $targets -Raw

        # Disable VerifyClickOnceSigningSettings
        $content = $content.Replace(
            '<VerifyClickOnceSigningSettings SignManifests="$(SignManifests)" ' + "`r`n" + '        />',
            '<VerifyClickOnceSigningSettings SignManifests="$(SignManifests)" Condition="''$(SignManifests)'' != ''false''" />'
        )

        # Disable ManageCertificateStore
        $content = $content.Replace(
            '<ManageCertificateStore',
            '<ManageCertificateStore Condition="''$(SignManifests)'' != ''false''"'
        )

        Set-Content `
            -Path $targets `
            -Value $content `
            -Encoding UTF8

        Write-Host "VSTO signing tasks successfully patched."
    - name: Build AutomationDesigner
      run: msbuild AutomationDesigner.sln /p:Configuration=Release /p:SignManifests=false

    - name: Upload AutomationDesigner
      uses: actions/upload-artifact@v4
      with:
        name: AutomationDesigner
        path: AutomationDesigner/bin/Release/*
